services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    ### hot reload using watch
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app
    ### hot reload using volumes
    # volumes:
    #   - ./web:/app
    #   - /app/node_modules
    # environment:
      # - CHOKIDAR_USEPOLLING=true
      # - WATCHPACK_POLLING=true
