pipeline {
    agent {
        node {
            label 'docker-agent-nodejs-1.0.2'
        }
    }
    stages {
        stage('Build') {
            steps {
                githubChecks name: 'build', status: 'in_progress'
                echo "Building..."
                githubChecks name: 'build', status: 'completed', conclusion: 'success'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}