pipeline {
    agent {
        docker {
            image 'jenkins-nodejs-agent:1.0.2'
            label 'jenkins-nodejs-agent:1.0.2'
            reuseNode true
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}