pipeline {
    agent {
        node {
            label 'docker-agent-nodejs-1.0.2'
        }
    }
    stages {
        stage('Build') {
            steps {
                githubChecks name: 'Build Stage', summary: 'Building the project', text: 'Starting build...'
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}